# Generated by Django 4.2.2 on 2023-06-25 09:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Isikud',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('isikutyyp', models.CharField(max_length=1)),
                ('isosauhing', models.BooleanField()),
                ('nimi', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('perenimi', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('isvalis', models.BooleanField()),
                ('kood', models.CharField(max_length=20, unique=True)),
                ('koodriik', models.CharField(max_length=2)),
                ('synniaeg', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Osauhing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('asutamiseKP', models.DateField()),
                ('kogukapital', models.IntegerField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('isik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OsauhingAPP.isikud')),
            ],
        ),
        migrations.CreateModel(
            name='Osauhing_Isikud',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('osauhinguOsa', models.IntegerField()),
                ('isasutaja', models.BooleanField()),
                ('isik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OsauhingAPP.isikud')),
                ('osauhing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OsauhingAPP.osauhing')),
            ],
        ),
    ]
