# Generated by Django 4.2.2 on 2023-06-25 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OsauhingAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isikud',
            options={'verbose_name': 'Isikud', 'verbose_name_plural': 'Isikud'},
        ),
        migrations.AlterModelOptions(
            name='osauhing',
            options={'verbose_name': 'Osauhing', 'verbose_name_plural': 'Osauhing'},
        ),
        migrations.AlterModelOptions(
            name='osauhing_isikud',
            options={'verbose_name': 'Osauhing_Isikud', 'verbose_name_plural': 'Osauhing_Isikud'},
        ),
        migrations.AlterField(
            model_name='isikud',
            name='perenimi',
            field=models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='isikud',
            name='synniaeg',
            field=models.DateField(blank=True, default=''),
        ),
    ]
