# Generated by Django 4.2.2 on 2023-06-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OsauhingAPP', '0002_alter_isikud_options_alter_osauhing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isikud',
            name='synniaeg',
            field=models.DateField(blank=True, default=None),
        ),
    ]
