# Generated by Django 4.2.2 on 2023-06-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OsauhingAPP', '0003_alter_isikud_synniaeg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isikud',
            name='synniaeg',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
