# Generated by Django 4.2.2 on 2023-06-25 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OsauhingAPP', '0004_alter_isikud_synniaeg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isikud',
            name='isikutyyp',
            field=models.CharField(choices=[('F', 'Füüsiline isik'), ('J', 'Juriidiline isik')], max_length=1),
        ),
        migrations.AlterField(
            model_name='isikud',
            name='perenimi',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
