# Generated by Django 4.2.2 on 2023-07-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OsauhingAPP', '0005_alter_isikud_isikutyyp_alter_isikud_perenimi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isikud',
            name='isvalis',
        ),
        migrations.RemoveField(
            model_name='isikud',
            name='koodriik',
        ),
        migrations.RemoveField(
            model_name='isikud',
            name='synniaeg',
        ),
    ]
