# Generated by Django 4.2.2 on 2023-07-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OsauhingAPP', '0006_remove_isikud_isvalis_remove_isikud_koodriik_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osauhing',
            old_name='asutamiseKP',
            new_name='asutamisekp',
        ),
    ]
