# Generated by Django 4.2.2 on 2023-07-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OsauhingAPP', '0007_rename_asutamisekp_osauhing_asutamisekp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osauhing',
            name='kogukapital',
            field=models.IntegerField(),
        ),
    ]
